# Generated by Django 5.1.2 on 2024-11-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ant',
            name='minimal_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='chest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.chest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
