# Generated by Django 5.1.2 on 2024-11-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userants',
            name='return_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
