# Generated by Django 5.1.2 on 2024-11-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userants',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
