# Generated by Django 5.1.2 on 2024-11-06 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_ant_minimal_cost_alter_user_chest_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.chest'),
        ),
    ]
