# Generated by Django 5.1.2 on 2024-11-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_userants_return_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boss_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='chest_open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
