# Generated by Django 5.1.2 on 2024-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_user_boss_date_alter_user_chest_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
