# Generated by Django 5.1.2 on 2024-11-11 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_user_chest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_image', models.CharField(max_length=255)),
                ('middle_cost', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='ant',
            name='chances',
        ),
        migrations.RemoveField(
            model_name='chest',
            name='chances',
        ),
        migrations.AddField(
            model_name='userants',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userants',
            name='return_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ant',
            name='minimal_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='chest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.chest'),
        ),
        migrations.CreateModel(
            name='ChestAntChance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('ant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ant')),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chest')),
            ],
        ),
        migrations.CreateModel(
            name='AntItemChance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('ant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ant')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='ServerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_update_time', models.DateTimeField(null=True)),
                ('current_boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.boss')),
            ],
        ),
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
        ),
    ]
