# Generated by Django 5.1.2 on 2024-11-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_item_remove_ant_chances_remove_chest_chances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.chest'),
        ),
    ]
