# Generated by Django 5.1.2 on 2024-11-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_chest_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='vetka', max_length=255),
            preserve_default=False,
        ),
    ]
