# Generated by Django 5.1.2 on 2024-11-12 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ant',
            name='expedition_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
            preserve_default=False,
        ),
    ]
