# Generated by Django 5.1.2 on 2024-11-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_ant_expedition_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ant',
            name='name',
            field=models.CharField(default='name-ant', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useritems',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
